export const initCharacterValues = {
  id: "",
  characterId: "",
  characterName: "",
  primaryCategory: "",
  categories: [],
  background: "",
  bio: "",
  firstPersonBio: "",
  visibility: "",
  publishingInfo: "",
  keywords: [],
  priority: 0,
  createdAt: "",
  updatedAt: null,
  active: "",
  attitude: "",
  extension: "",
  description: "",
};
